# ~/.bashrc: executed by bash(1) for non-login shells.

# Alises
alias python=python3
alias dc='docker compose'

. "$HOME/.cargo/env"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/spi/.lmstudio/bin"
# End of LM Studio CLI section
