set -g mouse on
set-hook -g after-new-session 'run-shell "tmux rename-session -t #{session_name} #{b:pane_current_path}"'

set -g status-style 'bg=#181825,fg=#cdd6f4'
set -g status-left '#[bg=#cba6f7,fg=#1e1e2e,bold] #S #[bg=#181825,fg=#cba6f7]'
set -g status-right '#[fg=#a6adc8]%Y-%m-%d #[fg=#89b4fa]%H:%M '
set -g window-status-format '#[fg=#a6adc8] #I:#W '
set -g window-status-current-format '#[bg=#313244,fg=#cdd6f4,bold] #I:#W '
set -g window-status-separator ''
set -g pane-border-style 'fg=#45475a'
set -g pane-active-border-style 'fg=#cba6f7'
set -g message-style 'bg=#313244,fg=#cdd6f4'
set -g message-command-style 'bg=#313244,fg=#f9e2af'
set -g mode-style 'bg=#f9e2af,fg=#1e1e2e'
set -g clock-mode-colour '#cba6f7'
