# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""

export PATH="$HOME/.local/bin:/usr/local/go/bin:$PATH"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

PROMPT='%F{#cba6f7}%n%f %F{#89b4fa}%~%f %(?.%F{#a6e3a1}❯.%F{#f38ba8}❯)%f '

# pipx path and autocompletion
autoload -U bashcompinit
bashcompinit
#eval "$(register-python-argcomplete pipx)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export SECRETS_DIR=~/repos/secrets

#if [[ -o interactive ]] && [[ -z "${TUTR_AUTOSTARTED:-}" ]] && [[ -z "${TUTR_SKIP_AUTOSTART:-}" ]]; then
#  export TUTR_AUTOSTARTED=1
#  exec tutr
#fi

export PATH="$PATH:/opt/nvim-linux-x86_64/bin"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/spi/.lmstudio/bin"
# End of LM Studio CLI section

# Attach interactive SSH logins to the persistent Herdr session.
if [[ -o interactive && -n "${SSH_TTY:-}" && "${HERDR_ENV:-}" != 1 ]] && command -v herdr >/dev/null 2>&1; then
  exec herdr
fi
